name: build & deploy
on: 
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches: 
    - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  docker-build:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run: docker build -t calculator -f path/to/Dockerfile .
      - name: run the conatiner
        run: docker run --name web_cal -p 8080:8080 calculator:latest
      - name : conatiner list
        run: docker ps -a
  health-check:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: check application health
        run: |
          echo "Waiting for the application to start..."
          sleep 3
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
          echo "Application responded with HTTP status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "Success! The calculator application is up and running."
          else
            echo "Error: Application health check failed! Container logs:"
            docker logs web_calculator
            exit 1
          fi
  suceess-msg:
    needs: health-check
    runs-on: ubuntu-latest
    steps:
      - name: viewing the sucess of deployment
        run: echo "Application deployed successfully""
  fail-msg:
    needs: [build-test,docker-build,health-check]
    runs-on: ubuntu-latest
    steps:
      - name: Application Deployment Failure
        run: echo "Application deployment failed"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - list files
        run: |
          pwd
          ls -la
          find . -iname "dockerfile*"
    
